name: Build APK

on:
  push:
    branches: [ principal ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies & AIDL
      run: |
        sudo apt-get update
        # On installe explicitement le paquet 'aidl' d'Ubuntu pour corriger la ligne 948
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev cmake aidl
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK with Buildozer
      run: |
        # Création préventive du dossier où Buildozer cherche 'aidl' pour court-circuiter l'erreur
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0/
        # On crée un lien symbolique de l'outil 'aidl' du système vers le dossier de Buildozer
        ln -s /usr/bin/aidl $HOME/.buildozer/android/platform/android-sdk/build-tools/34.0.0/aidl
        
        # Lancement de la compilation
        buildozer android debug
      env:
        AUTO_ACCEPT_LICENSE: "1"
